### ISSUE TITLE
Nested <li>'s

### ISSUE THREAD

**Issue by Julicolo** [ad-profundis/teamproject#3]
Het is niet correct om in een `<li>`, een andere `<li>` te stoppen.
De correcte structuur is altijd `<ul>` -> `<li>` -> `<span>` / `<p>` / whatever.

De fout bevind zich [hier](https://github.com/ad-profundis/teamproject/blob/master/index.php#L16)

**Comment by cschuijt-web** [comment]
ja ik zag al dat dat niet werkte en is niet langer van toepassing
