### ISSUE TITLE
JavaScript proceed warning suggestion

### ISSUE THREAD

**Issue by thomdr** [ad-profundis/teamproject#4]
There are some buttons that can have bad results if pressed by accident, e.g. delete buttons. Can you add a JavaScript warning for all input/button elements bearing the class `warning-trigger`, that asks if the user wants to proceed with the button press or cancel?

**Comment by Julicolo** [comment]
Ok I will get to this issue as soon as I have time, which likely won't be until tonight around 9'ish.
If I won't get to this today, I will definitely implement this around noon on Saturday.

**Comment by thomdr** [comment]
> Ok I will get to this issue as soon as I have time, which likely won't be until tonight around 9'ish.
> If I won't get to this today, I will definitely implement this around noon on Saturday.

Note that this is low priority, just a user friendly addition. If you're short on time/busy, it is completely understandable to push this aside
